### ISSUE TITLE
error MSB3073 More then one device/emulator

### ISSUE THREAD

**Issue by trampster** [jonathanpeppers/Mono.Profiler.Android#13]
When I try and run with the command:

```
dotnet build -t:BuildAndStartAotProfiling -f net7.0-android -p:AndroidSdkDirectory=/home/daniel/Android/Sdk
```

I get the following error:

```
adb: more than one device/emulator
/usr/share/dotnet/packs/Microsoft.Android.Sdk.Linux/33.0.95/tools/Xamarin.Android.Application.targets(45,5): error MSB3073: The command ""/home/daniel/Android/Sdk/platform-tools/adb"  shell setprop debug.mono.profile aot:port=9999" exited with code 1. [/home/daniel/Work/hydra-src/apps/Xamarin-PTToX/src/Pttox.Forms/Pttox.Forms.csproj::TargetFramework=net7.0-android]
```

How can I specify which device to use? removing the emulator would also work I guess, but I didn't add it and don't know how to remove it.

**Comment by jonathanpeppers** [comment]
This code is from Xamarin.Android (and still present in .NET 6+):

https://github.com/xamarin/xamarin-android/blob/b830f572b111e0c5379fd4194f260d2fd5a9e2fe/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Application.targets#L45

I think you should be able to set `-p:AdbTarget=-s1234` for a device with serial 1234, for example:

https://learn.microsoft.com/en-us/xamarin/android/deploy-test/building-apps/build-properties#adbtarget

**Comment by trampster** [comment]
I managed to stop the emulator which enabled me to profile
