### ISSUE TITLE
Error code 9009 - missing "aprofutil" executable

### ISSUE THREAD

**Issue by jonathanantoine** [jonathanpeppers/Mono.Profiler.Android#19]
Hello,

When following the steps (using this package or [the dotnet tracing documentation ones](https://github.com/dotnet/android/blob/main/Documentation/guides/tracing.md)), I have a code 9009 error.

It tries to uses the `aprof`` utiles from my `C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.143\tools` folder but its not in it.

Can you help me please ?

**Comment by jonathanantoine** [comment]
As always when creating an issue, I find the solution a few minutes later... 

For thos looking for the solution, its in this [readme file](https://github.com/jonathanpeppers/android-profiled-aot?tab=readme-ov-file#how-do-you-update-files-in-binaries-folder).

**Comment by jonathanpeppers** [comment]
If you add the NuGet package, `dotnet add package Mono.AotProfiler.Android`, it has `aprofutil` inside and configures it for you.

**Comment by jonathanantoine** [comment]
I was targeting a DotNet 8 app and it was not working.

Now I am struggling to use the documented tools but I still don't manage to make the app speak with the router and DotNet trace. If you have a walkthrough somewhere it would be very helpful.

Thanks for this package and answer anyway!❤️

**Comment by jonathanpeppers** [comment]
I have a YouTube video on `dotnet-trace`, etc.:
* https://youtu.be/hIYwz5dsZ6M

**Comment by jonathanpeppers** [comment]
This entire doc is Xamarin.Android:

* https://github.com/dotnet/android/blob/main/Documentation/guides/profiling.md#profiling-the-aot-compiler

So, yeah this package is best for now. There is a plan to make it work in-box, but I haven't gotten all the parties to agree how yet. Thanks!

**Comment by jonathanpeppers** [comment]
You might try this:
```
# clear the log
adb logcat -c
# enable more logging
adb shell setprop debug.mono.log default,assembly,debugger,mono_log_level=debug,mono_log_mask=all

# try it again

# save the log
adb logcat -d > log.txt
```

It should say in the Android log what is going on. Then you have to either reboot the device or this to clear the extra logging later: `adb shell setprop debug.mono.log "''"`

**Comment by jonathanantoine** [comment]
Hello, just clearing the logcat seems to have fixed the issue. Thanks **a lot** for your help.
