### ISSUE TITLE
Unable to profile

### ISSUE THREAD

**Issue by Syed-RI** [jonathanpeppers/Mono.Profiler.Android#9]
Got re-directed here from https://devblogs.microsoft.com/dotnet/performance-improvements-in-dotnet-maui/#profiled-aot 
I have a .NET MAUI project that targets .NET 7 iOS and Android. I've added the package as described in the readme followed by 
` dotnet build pathTo.csproj -t:BuildAndStartAotProfiling -p:AndroidEnableAotProfiler=true`

But getting 

`error MSB4057: The target "BuildAndStartAotProfiling" does not exist in the project.`

Probably a bit more detailed step by step guide would be novice like me. Appreciate your hard work Jonathan and thank you!

**Comment by jonathanpeppers** [comment]
If it is a multi-targeted project, do you just need to put `-f net7.0-android`?

PRs to the docs are welcome, thanks!

**Comment by Syed-RI** [comment]
Thanks Jonathan! That did the trick! I'll get a PR from my personal profile in a bit. I do have few follow up questions though.

- Should we profile again if there is a dependency change? i.e. lets say I dropped using Skiasharp
- Whats the optimised settings to use the AOT + LLVM + Custom profile? Currently I have the following:
```
<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net7.0-android|AnyCPU'">
    <!-- https://devblogs.microsoft.com/dotnet/performance-improvements-in-dotnet-maui/#profiled-aot -->
    <RunAOTCompilation>true</RunAOTCompilation>
    <AndroidEnableProfiledAot>true</AndroidEnableProfiledAot>
    <EnableLLVM>true</EnableLLVM>
    <MauiUseDefaultAotProfile>false</MauiUseDefaultAotProfile>
  </PropertyGroup>
<ItemGroup>
    <AndroidAotProfile Include="custom.aprof"/>
 </ItemGroup>
```

Something tells me that is not right as Im not seeing any improvements on startup or app performance but the build time has ballooned over 30 mins

**Comment by jonathanpeppers** [comment]
@Syed-RI maybe turn off `EnableLLVM`, I have not found an app yet where it helps anything.

If you want to see what is in the profile, here is an example to print the list of methods out of it:

https://github.com/xamarin/xamarin-android/blob/e694ba52a0cf5f45b213c8902bdbfb0ed348374a/src/profiled-aot/Directory.Build.targets#L53-L54

    dotnet path/to/aotprofile-tool.dll -f custom.aprof

So if you removed SkiaSharp, and SkiaSharp methods are in there -- you might record a new profile.
